### ISSUE TITLE
Enable sleep button

### ISSUE THREAD

**Issue by timuric** [pauloconnor/das_keyboard#1]
Thank you so much for sharing your configuration. It did help to setup media keys on my das keyboard. Any tip on how did you figured out the Raw values of the keys? I would like to map sleep button as well, but I don't have a clue how to do it. Thanks in advance.

**Comment by timuric** [comment]
Ah never mind, I figured that out :)

**Comment by pauloconnor** [comment]
@timuric I'd love if you could share your code for that in a PR. I'm sure others will have the same issue.

**Comment by timuric** [comment]
@pauloconnor actualy there was no issue. Apperantly you just have to press and hold for a while, something I was not aware of :D

**Comment by pauloconnor** [comment]
Ha, awesome. Thanks!
